### ISSUE TITLE
Unable to Connect to Server! Received Status Code: 0. A status code of 0, could mean the host is unreacheable or nothing is listening on the given port. 

### ISSUE THREAD

**Issue by iskyd** [ElasticHQ/elasticsearch-HQ#233]
I download elasticsearch-HQ and start it but I can't connect to host.
This seems to be an error only for elasticsearch-HQ.
`curl -XGET 'localhost:9200/_cluster/health'`
This return me a good answer. Also if I connect to localhost:9200 I receive 

```
{
  "status" : 200,
  "name" : "Toro",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.4",
    "build_hash" : "0d3159b9fc8bc8e367c5c40c09c2a57c0032b32e",
    "build_timestamp" : "2015-12-15T11:25:18Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

How can I fix this?

**Comment by arruor** [comment]
Hello there,
which version of HQ are you using? For Elasticsearch 1.7 you have to use version 1.0. To install it please use following command:
```
/path/to/es-share-dir/bin/plugin install royrusso/elasticsearch-HQ/v1.0.0
```

**Comment by CaredduMattia** [comment]
Using plugin all works right. With Download/Install i get this error.

**Comment by jbfarez** [comment]
Hi there, I got this error too when I want to install HQ in "standalone" mode (not as a plugin).

**Comment by jbfarez** [comment]
Hey @CaredduMattia, I think it could be due to a cross-origin restriction. Maybe you have to allow cross-origin access (be careful, it could be a security risk depending your network security).
For me, those settings solved the issue :
```yml
http.cors.enabled : true
http.cors.allow-origin : "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length
```
Hope this could help.

Cheers !
