### ISSUE TITLE
Vagrant Elasticsearch-HQ help. 

### ISSUE THREAD

**Issue by rlam3** [ElasticHQ/elasticsearch-HQ#238]
What other settings do i need to make for this to work with vagrant? 

I keep getting the following error

```
Unable to Connect to Server! Received Status Code: 0. A status code of 0, could mean the host is unreacheable or nothing is listening on the given port. Did you enable CORS?
```

**My settings**

``` yml
#elasticsearch.yml

network.host: 0.0.0.0

http.cors.enabled: true
http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?/

script.inline: on
script.indexed: on
```

I already am forwarding the ports and am able to curl.

``` ruby
#Vagrantfile

  config.vm.network "private_network", ip: "192.168.0.200"
  config.vm.network :forwarded_port, guest: 9200, host: 9200, auto_correct: true
```

``` bash
#shell - not vagrant ssh

curl 192.168.0.200:9200
{
  "name" : "Yandroth",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

```

Thanks!
