### ISSUE TITLE
Cluster Connection Failed

### ISSUE THREAD

**Issue by altafsayani** [ElasticHQ/elasticsearch-HQ#419]
I am trying to setup elasticsearch with elasticsearch hq using docker compose. But when I try to connect to my elasticsearch server using elasticsearch hq it showing "Cluster connection failed! Check server log if problem persist" error.

Here is my docker-compose.yml file

```
version: '3.1'

services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch_server
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./db:/usr/share/elasticsearch/data
  elasticsearch_hq:
    image: elastichq/elasticsearch-hq
    container_name: elasticsearch_hq
    environment:
      - "HQ_DEFAULT_URL=http://localhost:9200"
    ports:
      - 5000:5000
```
