### ISSUE TITLE
HQ_DEFAULT_URL does not work in deployment

### ISSUE THREAD

**Issue by lucaskenda** [ElasticHQ/elasticsearch-HQ#481]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **ElasticHQ Version**: release-v3.5.0 and v3.6.0-alpha
- **Elasticsearch Version**: Opendistro 1.0.1 (7.0.1)
- **Docker version**: Docker version 18.09.6, build 481bc77156 

### Issue Description

I am executing the following deployment in Kubernetes but it does not initialize with HQ_DEFAULT_URL environment variable. It just list 127.0.0.1:9200

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-hq
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: hq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: hq
    spec:
      containers:
      - name: elasticsearch-hq
        image: elastichq/elasticsearch-hq:release-v3.5.0
        env:
        - name: HQ_DEFAULT_URL
          valueFrom:
            secretKeyRef:
              name: elasticsearch-sec
              key: elasticsearch_url
        resources:
          limits:
            cpu: 0.5
        ports:
        - containerPort: 5000
          name: http
```

### Source Code / Logs

HQ_DEFAULT_URL is loaded correctly:

![Screenshot from 2019-07-25 16-00-38](https://user-images.githubusercontent.com/4048688/61901256-b9446a80-aef5-11e9-872f-902eb5e936db.png)

But I get this default value:

![image](https://user-images.githubusercontent.com/4048688/61901332-e98c0900-aef5-11e9-9a9a-9d138542b588.png)

Thanks!
Lucas

**Comment by royrusso** [comment]
Please see if the latest docker release fixes this. Someone did a https://github.com/ElasticHQ/elasticsearch-HQ/pull/476 that may address this.

**Comment by OphyTe** [comment]
I think this doesn't work anymuch better with your add 0a43f042b8202f14bc0c8e13d6d2c9f0a4ccb2c6

I'm running the 3.5.4 version from Docker Swarm and no env var is taken into account ...

**Comment by OphyTe** [comment]
I've tested HQ_DEFAULT_URL and HQ_DEBUG=False (because it's true by default on my installation) on a swarm environment

**Comment by royrusso** [comment]
Interesting. I'll try with docker compose, because I tested within Pycharm and it worked. Stay tuned.

**Comment by OphyTe** [comment]
Hi, does this means that you cannot reproduce my bug or that it will be
resolved in the future?

**Comment by royrusso** [comment]
I couldn't reproduce with the latest release. I tested with a sample docker-compose that I committed here (https://github.com/ElasticHQ/elasticsearch-HQ/blob/develop/example/docker-compose.yml), as some others were having trouble with containerized HQ and ES working together.

That file will start up the latest HQ from dockerhub, and ES 2.x. It will auto-populate `HQ_DEFAULT_URL` in the address bar. Try running the compose file and let me know if it doesn't work, then we can reopen this perhaps.

**Comment by OphyTe** [comment]
I've just tested it and it didn't work.
The only adjustment I did was on the network driver that I pass to `overlay` because `bridge` didn't work with Swarm.

And for the record, in my previous tests, my elastic stack was in 6.5.1-oss.

**Comment by royrusso** [comment]
Can you post your docker-compose file?

**Comment by aceeric** [comment]
I realize this issue is old. I just tried with v3.5.12 in Kubernetes (air-gapped) and as described above, the default url on the main page is http://localhost:9200. If I paste in the correct URL in the UI then it connects and works great. The logs have an initial entry:
```
DEBUG elastichq status.get:63 {"name": "ElasticHQ", installed_version: "3.5.12",
"current_stable_version": "Err: unable to reach elastchq.org", "tagline": "You know, for
ElasticSearch", "clusters": [], "default_url":
https://elastic:hz9p6uTw11kQQQQQFz23423PY23dg@nxelastic-es-http:9200"}
```
Is it possible that - in an air-gapped environment - the inability to connect to elastichq.org causes it to exit some initialization path?

I'm standing up ElasticHQ with a `Deployment` manifest, defining the environment variables as I understand the docs to require:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastichq
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: elastichq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elastichq
    spec:
      containers:
      - name: elastichq
        image: elastichq/elasticsearch-hq:release-v3.5.12
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: HQ_ENABLE_SSL
          value: 'True'
        - name: HQ_CA_CERTS
          value: /usr/share/elasticsearch/config/http-certs/ca.crt
        - name: HQ_VERIFY_CERTS
          value: 'False'
        - name: ELASTICPASS
          valueFrom:
            secretKeyRef:
              name: nxelastic-es-elastic-user
              key: elastic
        - name: HQ_DEFAULT_URL
          value: https://elastic:$(ELASTICPASS)@nxelastic=es=htttp:9200
        volumeMounts:
        - name: nxelastic-es-htttp-certs-internal
          mountPath: /usr/share/elasticsearch/config/http-certs
    volumes:
    - name: nxelastic-es-htttp-certs-internal
       secret:
         secretName: nxelastic-es-htttp-certs-internal
```

This ElasticSearch cluster is being provisioned by [Elastic Cloud on Kubernetes](https://github.com/elastic/cloud-on-k8s) . The ES cluster is functioning fine and - ElasticHQ works fine as well - once I manually enter the URL on the greeting page. But the UI doesn't seem to pick up the default URL from the Pod environment variable...
